apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: presync-root
  namespace: default
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/choejwoo/argocd-example-apps.git
    targetRevision: HEAD
    path: presync-selfheal/root
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

